// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCejr2iQzL_yW9QWzY1FJxIvzW-PjCXqA8',
    appId: '1:1039212491012:web:dac45a25b7e45ea49e2051',
    messagingSenderId: '1039212491012',
    projectId: 'fir-sign-d584d',
    authDomain: 'fir-sign-d584d.firebaseapp.com',
    storageBucket: 'fir-sign-d584d.appspot.com',
    measurementId: 'G-5B012V3YR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBskoy7GmSL_n48OHjjvC-bCb-4YvGd_PU',
    appId: '1:1039212491012:android:9b8ecaebcfbbe2889e2051',
    messagingSenderId: '1039212491012',
    projectId: 'fir-sign-d584d',
    storageBucket: 'fir-sign-d584d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpiEyTMYtdhBSF0aMg-ibp78d9BE5R1Ow',
    appId: '1:1039212491012:ios:11d790e3d56d80db9e2051',
    messagingSenderId: '1039212491012',
    projectId: 'fir-sign-d584d',
    storageBucket: 'fir-sign-d584d.appspot.com',
    iosBundleId: 'com.example.firebaseGoogleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpiEyTMYtdhBSF0aMg-ibp78d9BE5R1Ow',
    appId: '1:1039212491012:ios:a98d8abecefe76c59e2051',
    messagingSenderId: '1039212491012',
    projectId: 'fir-sign-d584d',
    storageBucket: 'fir-sign-d584d.appspot.com',
    iosBundleId: 'com.example.firebaseGoogleSignin.RunnerTests',
  );
}
